### ISSUE TITLE
Provide data type validation for default value of Argument

### ISSUE THREAD

**Issue by tedyu** [argparse4j/argparse4j#113]
Given the following code:
```
        parser.addArgument("--message-create-time")
                .required(false)
                .setDefault(-1)
                .type(Long.class)
```
Argument class should provide data type validation for default value.
In the above case, the proper default value should be -1L

**Comment by jstuyts** [comment]
I think this would be a valuable addition, but unfortunately it is too costly. See below.

This can only be done if `setDefault(…)` is always invoked after `type(…)`, as the default type is `StringArgumentType`. So in your example `setDefault(-1)` would fail because at that moment a string is still expected.

Adding a new requirement about the order in which `setDefault(…)` and `type(…)` have to be called, will break backward incompatibility. That is the main reason for not adding the validation.

The type checking would also have to be recursive, because the default value can be a collection. This makes the implementation more complex, and it may be even impossible to behave correctly under all conditions, as element types of collections, etc. may not be known.

We could add another method `addTypeWithDefault(...)`. But this too would break backward incompatibility. And 6 overloaded methods would have to be introduced, because both `setDefault(...)` and `type(...)` have multiple overloads. It would also introduce an inconsistency: `addTypeWithDefault(...)` does check that the default value is of the correct type, but the combination of `setDefault(...)` and `type(...)` does not.

So unless there is a compelling use case besides a developer not paying enough attention, I am against implementing this.

**Comment by jstuyts** [comment]
This won't be implemented. It only prevents a problem that can easily be fixed before shipping the code.. Breaking backward compatibility for it is not worth the added benefit.
