### ISSUE TITLE
FileVerification.verify doesn't properly handle 'or'

### ISSUE THREAD

**Issue by njdoyle** [argparse4j/argparse4j#115]
I'm taking a file as an argument parameter. I set the type to this:
```
new FileArgumentType().verifyCanWrite().or().verifyNotExists().verifyCanWriteParent()
```
What I want to check is if I can write to this file or that I can create and write to this file. This doesn't work because `FileVerification.verify()` only processes `or` cases if `verifyPresenceAndType` fails but not if `verifyPermissions` fails. `or` cases should be processed if either of these two checks fail.

**Comment by jstuyts** [comment]
I agree that `or()` should work for all checks up to that point. The documentation also does not state that it will only work for the presence/type verification. I will see if I can find the time to fix it. A release might take a little longer though.

I do advise to add `verifyIsFile()` before `verifyCanWrite()`, because the latter can return `true` for directories too.

**Comment by jstuyts** [comment]
Please verify the changes I made. If they work for you, you can close this issue.

**Comment by jstuyts** [comment]
@njdoyle Can you verify that it works for you now? If you do not want to build argparse4j yourself, you can find a build here: https://1drv.ms/u/s!Ag13WlvRSi9Ytbt2RhRrSpA0ABOfPQ?e=m2uqDA

If it works for you, you can close this issue.
