### ISSUE TITLE
Enable to share arguments of parent parser in subparser like python

### ISSUE THREAD

**Issue by Anurag2408** [argparse4j/argparse4j#120]
I want to share some common arguments of main parser in the subparser like we do in python argParser library. 
 for reference-
`sub_parser1= sub_parser.add_parser('abc', parents=[parent_parser])`

can we do like this in JavaArgParse4J library. I couldn't find any way to share the argument of main parser in java argParse library.

**Comment by jstuyts** [comment]
Does this do what you want to do: https://argparse4j.github.io/usage.html#sub-commands ? In the example argument `foo` is shared by the parsers for `a` and `b`.

The only shortcoming that I see is that you cannot view all arguments of a sub parser and all of its ancestors at the same time. To get the full picture you have to ask for help multiple times.

**Comment by Anurag2408** [comment]
jstuyts thanks! yeah exactly sub-commands , I want to do. I tried this but the problem what I encountered that I can't override the main parser argument value in subparser. 

for more clarity , go through example code:

  In this example, there is  `foo` is main parser and `a` & `b ` are sub parser. when we run sub parser from command line and try to override the default value of `--name` argument of main  `foo` parser in  sub parser `a`, it don't work. (simply print on console unrecognized arguments: '--name')


     
        ArgumentParser parser = ArgumentParsers.newFor("foo").build();
        parser.addArgument("--email").setDefault("abc@xyz.com").type(String.class).help("default email");
        parser.addArgument("--name").setDefault("James").type(String.class).help("default name");

 
       Subparsers subparser=parser.addSubparsers().help("Subcommand");
    
        Subparser aSubparser= subparser.addParser("a").help("Subparser fo a");
        aSubparser.addArgument("--address").type(String.class).required(true);
        aSubparser.setDefault("which", "a");
        
        
        Subparser bSubparser= subparser.addParser("b").help("Subparser for b");
        bSubparser.addArgument("--phonenumber").type(String.class);
        bSubparser.setDefault("which", "b");`






`

**Comment by jstuyts** [comment]
These are the things that I observe:
* An argument for the main parser must preceed the name of a sub parser. This allows both the main and the sub parser to have an argument with the same name. I think this is confusing, but some people may find this useful:
    ```
    --arg mainVal subparserName --arg subVal
    ```
* Assuming you mean `name` where you use `which` In your example, providing a value for `name` for the main parser has no effect:
    ```
    --name mainName a --addresss someAddress
    ```
    Expected: `Namespace(address=someAddress, name=mainName, email=abc@xyz.com)`
    Actual: `Namespace(address=someAddress, name=a, email=abc@xyz.com)`
    This looks like a bug to me. But which one of these 2 bugs below is it?
    1. Setting a default value for an argument not defined on a sub parser is allowed, when it should result in an error while building the sub parser.
    2. Setting a default value for an argument of the main parser on a sub parser, always results in the default value if the sub parser name is selected in the arguments, when it should result in the explicit value in the arguments.

I do not know the exact behavior of the Python implementation, but I lean towards bug i. Because arguments of the main parser and sub parsers are separate from each other in argparse4j, it does not feel right to allow specifying a default on the sub parser for an argument of the main parser.

There is a simple workaround to get what you want. Simply don't specify a default value, and in code choose the correct default value for the sub parser that was chosen.

**Comment by jstuyts** [comment]
I tested the Python implementation and as far as I can tell it behaves in the same way as argparse4j. Can you give another (and minimal) example, with sets of arguments, and per set of argument the expected and actual result? Thanks in advance.

**Comment by jstuyts** [comment]
No response to request for more information.
